export interface Theme {
  id: string
  name: string
  blurb: string
  fonts?: { display: string; serif: string; body: string; mono: string }
  tokens: Record<string, string>
}

// Every theme sets the same token names the real app already uses, plus a few
// that are currently hardcoded in globals.css. Picking a winner is then a
// copy-paste of one :root block, not a restyle.
export const THEMES: Theme[] = [
  // — the four workflow-designed finalists (contrast-audited, judged) —
  {
    id: 'phosphor',
    name: 'Phosphor',
    blurb: 'The winner on fidelity. Green instrument panel — hairlines do the work, mint only where your thumb goes, violet reserved for nav. Serif greeting, mono labels.',
    fonts: { display: 'Anton', serif: 'Instrument Serif', body: 'Inter', mono: 'IBM Plex Mono' },
    tokens: {
      '--paper': '#0B0D0A',
      '--white': '#10130F',
      '--ink': '#F1EEE5',
      '--muted': '#8E958A',
      '--divider': '#404e3f',
      '--field': '#5d5d5d',
      '--line': '#5A6D58',
      '--soft': '#171B16',
      '--mint': '#5CE8A6',
      '--mint-dark': '#7DEBB8',
      '--danger': '#E8836A',
      '--violet': '#B57DF7',
      '--on-accent': '#04140C',
      '--page-grad-a': '#0E1210',
      '--page-grad-b': '#070907',
      '--frame-inset': '#060806',
      '--frame-border': '#5F725D',
      '--copy-text': '#A7AEA3',
      '--shadow': 'rgba(0, 5, 2, .72)',
    },
  },
  {
    id: 'instrument-black',
    name: 'Instrument Black',
    blurb: 'Tied first. The ruthless-mono take — near-monochrome, accent almost only on completed sets and the CTA. Numbers read like instrument readouts.',
    fonts: { display: 'Anton', serif: 'Instrument Serif', body: 'Inter', mono: 'JetBrains Mono' },
    tokens: {
      '--paper': '#0B0D0A',
      '--white': '#121610',
      '--ink': '#F1EEE6',
      '--muted': '#869084',
      '--divider': '#424d40',
      '--field': '#5d5d5d',
      '--line': '#5D6C59',
      '--soft': '#191E17',
      '--mint': '#6FE3AC',
      '--mint-dark': '#9CC8B0',
      '--danger': '#DE7B62',
      '--violet': '#B37AF6',
      '--on-accent': '#061109',
      '--page-grad-a': '#0A0C09',
      '--page-grad-b': '#050604',
      '--frame-inset': '#060805',
      '--frame-border': '#556151',
      '--copy-text': '#A7AFA2',
      '--shadow': 'rgba(0, 0, 0, 0.66)',
    },
  },
  {
    id: 'nightpress',
    name: 'Nightpress',
    blurb: 'The editorial take — condensed display + serif italic as the whole identity. Most magazine-like.',
    fonts: { display: 'Anton', serif: 'Instrument Serif', body: 'Inter', mono: 'IBM Plex Mono' },
    tokens: {
      '--paper': '#0B0D0A',
      '--white': '#12150F',
      '--ink': '#F2EDE3',
      '--muted': '#9EA495',
      '--divider': '#424d3b',
      '--field': '#5d5d5d',
      '--line': '#5D6B53',
      '--soft': '#191D16',
      '--mint': '#4FDDA2',
      '--mint-dark': '#8CF2CB',
      '--danger': '#E88A6A',
      '--violet': '#A46BF2',
      '--on-accent': '#07130D',
      '--page-grad-a': '#101310',
      '--page-grad-b': '#060806',
      '--frame-inset': '#0E110C',
      '--frame-border': '#5A664F',
      '--copy-text': '#A8AC9E',
      '--shadow': 'rgba(3, 6, 4, 0.68)',
    },
  },
  {
    id: 'violet-instrument',
    name: 'Violet Instrument',
    blurb: 'Violet as the primary accent, green demoted to data. Judges ranked it last — here for comparison.',
    fonts: { display: 'Anton', serif: 'Instrument Serif', body: 'Inter', mono: 'JetBrains Mono' },
    tokens: {
      '--paper': '#0B0E0C',
      '--white': '#121614',
      '--ink': '#F0EEE7',
      '--muted': '#949C96',
      '--divider': '#454f4a',
      '--field': '#5d5d5d',
      '--line': '#616F67',
      '--soft': '#191E1B',
      '--mint': '#A97BFF',
      '--mint-dark': '#5BE9A6',
      '--danger': '#F2704F',
      '--violet': '#7C4DE0',
      '--on-accent': '#150A2B',
      '--page-grad-a': '#090C0A',
      '--page-grad-b': '#13111B',
      '--frame-inset': '#151A17',
      '--frame-border': '#5F6C64',
      '--copy-text': '#B9C0BA',
      '--shadow': 'rgba(4, 2, 12, 0.62)',
    },
  },
  // — earlier quick variants kept for comparison —
  {
    id: 'midnight-mint',
    name: 'Midnight Mint',
    blurb: 'The straight inversion. Same mint, same shapes, lights off. Safest for brand continuity.',
    tokens: {
      '--paper': '#0b0f0d',
      '--white': '#141a17',
      '--ink': '#eef2ef',
      '--muted': '#8b968f',
      '--divider': '#191e1c',
      '--field': '#5d5d5d',
      '--line': '#232b27',
      '--soft': '#1a221e',
      '--mint': '#73e2b8',
      '--mint-dark': '#73e2b8',
      '--danger': '#e08585',
      '--page-grad-a': '#0d120f',
      '--page-grad-b': '#080b09',
      '--frame-inset': '#0e1310',
      '--frame-border': '#252d29',
      '--copy-text': '#a3aea7',
      '--shadow': 'rgba(0, 0, 0, .55)',
      '--on-accent': '#06130e',
    },
  },
  {
    id: 'oled',
    name: 'OLED',
    blurb: 'True black, hairline borders, no gradients. Maximum contrast in a bright gym, easiest on phone battery.',
    tokens: {
      '--paper': '#000000',
      '--white': '#0a0a0a',
      '--ink': '#ffffff',
      '--muted': '#8a8a8a',
      '--divider': '#161616',
      '--field': '#5d5d5d',
      '--line': '#1f1f1f',
      '--soft': '#141414',
      '--mint': '#5cf2b6',
      '--mint-dark': '#5cf2b6',
      '--danger': '#ff7b7b',
      '--page-grad-a': '#000000',
      '--page-grad-b': '#000000',
      '--frame-inset': '#000000',
      '--frame-border': '#242424',
      '--copy-text': '#9a9a9a',
      '--shadow': 'rgba(0, 0, 0, .8)',
      '--on-accent': '#00140c',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    blurb: 'Warm neutral grey, softer edges, mint held back for actions only. Reads premium and calm rather than techy.',
    tokens: {
      '--paper': '#16171a',
      '--white': '#1e2023',
      '--ink': '#f0efec',
      '--muted': '#9a9892',
      '--divider': '#212225',
      '--field': '#5d5d5d',
      '--line': '#2e3034',
      '--soft': '#26282c',
      '--mint': '#7fe3bd',
      '--mint-dark': '#8fdcc0',
      '--danger': '#e59292',
      '--page-grad-a': '#1a1b1e',
      '--page-grad-b': '#121316',
      '--frame-inset': '#191a1d',
      '--frame-border': '#33363a',
      '--copy-text': '#a8a6a1',
      '--shadow': 'rgba(0, 0, 0, .5)',
      '--on-accent': '#0b1a14',
    },
  },
  {
    id: 'steel',
    name: 'Steel',
    blurb: 'Desaturated blue-black. Cooler and more instrument-like — closer to a data tool than a fitness app.',
    tokens: {
      '--paper': '#0b0e13',
      '--white': '#131820',
      '--ink': '#e9eef5',
      '--muted': '#828d9c',
      '--divider': '#171d25',
      '--field': '#5d5d5d',
      '--line': '#212934',
      '--soft': '#182029',
      '--mint': '#6fe0c0',
      '--mint-dark': '#6fe0c0',
      '--danger': '#e28a8a',
      '--page-grad-a': '#0e131a',
      '--page-grad-b': '#080b0f',
      '--frame-inset': '#0f141b',
      '--frame-border': '#242d39',
      '--copy-text': '#9aa5b2',
      '--shadow': 'rgba(0, 0, 0, .6)',
      '--on-accent': '#03150f',
    },
  },
  {
    id: 'carbon-lime',
    name: 'Carbon Lime',
    blurb: 'Near-black with a brighter, punchier accent. Most energetic — the one that reads loudest on camera.',
    tokens: {
      '--paper': '#0a0b09',
      '--white': '#121410',
      '--ink': '#f2f4ee',
      '--muted': '#8d9285',
      '--divider': '#191c12',
      '--field': '#5d5d5d',
      '--line': '#242719',
      '--soft': '#191c15',
      '--mint': '#b6f24a',
      '--mint-dark': '#c2f766',
      '--danger': '#ef8080',
      '--page-grad-a': '#0d0f0b',
      '--page-grad-b': '#070806',
      '--frame-inset': '#0f110d',
      '--frame-border': '#282c1d',
      '--copy-text': '#a1a698',
      '--shadow': 'rgba(0, 0, 0, .6)',
      '--on-accent': '#111a02',
    },
  },
]
